### ISSUE TITLE
Get assets from manifest if available

### ISSUE THREAD

**Issue by larrybotha** [fixate/pw-mvc-boilerplate#17]
Manifest to be built to assets/rev-manifest.json

Manifest must:

- be optional
- have no external library dependencies
- only be read when in production mode
- to be handled from within render_scripts: https://github.com/fixate/pw-mvc-boilerplate/blob/a48ef44e657f3b00627b1cd4fb22e88682d8c573/controllers/traits/javascript.php#L38-L60 (requires a new Trait for manifests that has a method called from within render_scripts. Stylesheets Trait should be created so that it may also benefit from manifests)

Example method from gulp-rev: https://github.com/sindresorhus/gulp-rev/blob/master/integration.md#approach-3---php-reads-the-manifest-and-provides-asset-names
Ignore handlebars implementation, we have js_add_script method available to us.

**Comment by dewald-laubscher** [comment]
For the manifest files containing the md5# filename, we will add that to the generator-fixate-pw gulp tasks. Am I correct?

**Comment by larrybotha** [comment]
@dewald-laubscher ye, gulp-rev should be available once generated with yeoman

**Comment by dewald-laubscher** [comment]
To whom it may concern here is my progress on this task:
- Implemented a global to manage manifest
- Added to the assets function of the view class an implementation of said class

Outstanding Tasks:
- Implement a file reference to built and un-built assets
- Manifest will point to built else normal file
- Gulp on the generator-fixate-pw has been updated with the gulp-rev task, however needs more tweaking

Repo resides on github.com/dewald-laubscher  under the fork pw-mvc-boilerplate

**Comment by larrybotha** [comment]
#20
