### ISSUE TITLE
debug toggler

### ISSUE THREAD

**Issue by dewwwald** [fixate/pw-mvc-boilerplate#25]
The issue is created because the fix referenced in the commit will surely break groupElement option for the plugin.

https://github.com/fixate/pw-mvc-boilerplate/commit/12ae16cb07999d247a90a4c038ec078b0e46481f

**Comment by larrybotha** [comment]
toggler rewritten with tests:
https://github.com/fixate/pw-mvc-boilerplate/commit/ad0753aaa04baadf91d2f61db751c7481e1c0289
https://github.com/fixate/pw-mvc-boilerplate/commit/06f95f96d67afefe2f78574007608a0dd529d0ef
