### ISSUE TITLE
option no toggle container

### ISSUE THREAD

**Issue by dewwwald** [fixate/pw-mvc-boilerplate#26]
Add an option for a container that wont fire the toggler when an action is preformed in the container.

**Comment by larrybotha** [comment]
toggler rewritten with tests:
https://github.com/fixate/pw-mvc-boilerplate/commit/ad0753aaa04baadf91d2f61db751c7481e1c0289
https://github.com/fixate/pw-mvc-boilerplate/commit/06f95f96d67afefe2f78574007608a0dd529d0ef

Toggler by default doesn't close when click events are fired from within target
